name: Push to Azure Container Registry
on:
  push:
    branches:
      - main

jobs:
  push-to-azure-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: gestiondelaconfiguracion.azurecr.io
          username: gestiondelaconfiguracion
          password: ylnRhlkS6NUXcFH9R2XjwoOHk5wsL4UgGzWHO467JA+ACRADXcGr

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker image to Azure Container Registry
        run: |
            docker tag kalichhe/petclinic:latest gestiondelaconfiguracion.azurecr.io/kalichhe/petclinic:${{ github.sha }}
            docker push gestiondelaconfiguracion.azurecr.io/kalichhe/petclinic:${{ github.sha }}