name: Docker Build and Push to ACR

on:
  push:
    branches:
      - maven

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t kalichhe/petclinic .
        
      - name: Push to Docker Hub
        run: docker push kalichhe/petclinic

      - name: Login to Azure Container Registry
        run: az acr login --name gestiondelaconfiguracion

      - name: Push to Azure Container Registry
        run: docker push gestiondelaconfiguracion.azurecr.io/kalichhe/petclinic
